quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgre_suri}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/Suri_firuvet}

quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=false

quarkus.http.port=${PORT:8081}

quarkus.cxf.path=/soap
quarkus.cxf.endpoint."/mascotas".implementor=com.surifiruvet.soap.MascotaWebServiceImpl
quarkus.cxf.endpoint."/clientes".implementor=com.surifiruvet.soap.ClienteWebServiceImpl
quarkus.cxf.endpoint."/citas".implementor=com.surifiruvet.soap.CitaWebServiceImpl
quarkus.cxf.endpoint."/catalogos".implementor=com.surifiruvet.soap.CatalogoWebServiceImpl
